kind: pipeline
type: docker
name: default


concurrency:
  limit: 1

steps:

- name: build-atmosphere-runner  
  image: appleboy/drone-ssh
  environment:
    GITUSER:
      from_secret: gituser
    GITPASS:
      from_secret: gitpass
  settings:
    host: atmosphere.innovare.es
    username:
      from_secret: ssh_dev_user
    password:
      from_secret: ssh_dev_password
    port: 22
    envs:
      - gituser
      - gitpass
    script:
      - cd /home/developer/Atmosphere/atmosphere-runner/       
      - git pull https://$${GITUSER}:$${GITPASS}@gogs.innovare.es/INNOVARE/atmosphere-runner
      - sudo docker build --tag atmosphere:atmosphere-runner .

- name: deploy-atmosphere
  image: appleboy/drone-ssh
  environment:
      DO_KEY:
        from_secret: do_key
      DATABASE_PASSWORD:
        from_secret: database_password
  settings:
    host: atmosphere.innovare.es
    username:
      from_secret: ssh_dev_user
    password:
      from_secret: ssh_dev_password
    port: 22
    envs:
      - do_key
      - database_password
    script:
      - cd /home/developer/Atmosphere/Atmosphere/
      - sudo do_key=$${DO_KEY} database_password=$${DATABASE_PASSWORD} VERSION_TAG=${DRONE_COMMIT} docker-compose down
      - sudo do_key=$${DO_KEY} database_password=$${DATABASE_PASSWORD} VERSION_TAG=${DRONE_COMMIT} docker-compose up -d
      - sudo docker image prune
      - sudo docker volume prune
