name: Deploy and update (release)
on:
  release:
    types: [published]
jobs:
  Push-To-Registry-And-Deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME_ATMOSPHERE }}
          password: ${{ secrets.DOCKER_PASSWORD_ATMOSPHERE }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: innovaresoftware/atmosphere-runner

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            runner_url=${{ secrets.RUNNER_URL_ATMOSPHERE }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_ATMOSPHERE }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_ATMOSPHERE }} >> ~/.ssh/known_hosts

      - name: Deploy in server
        run: ssh ${{ secrets.SSH_USER_ATMOSPHERE }}@${{ secrets.SSH_HOST_ATMOSPHERE }} 'sudo docker pull innovaresoftware/atmosphere-runner:latest && sudo docker pull innovaresoftware/atmosphere:latest && cd '"${{secrets.SSH_HOST_DIR_ATMOSPHERE}}"' && sudo VERSION_TAG='"${{ github.ref_name}}"' do_key='"${{ secrets.DO_KEY_ATMOSPHERE }}"'  database_password='"${{secrets.GENERATED_PASSWORD_ATMOSPHERE}}"' mail_username='"${{secrets.MAIL_USERNAME_ATMOSPHERE}}"' mail_password='"${{secrets.MAIL_PASSOWRD_ATMOSPHERE}}"' mail_from='"${{secrets.MAIL_FROM_ATMOSPHERE}}"' mail_port='"${{secrets.MAIL_PORT_ATMOSPHERE}}"' mail_server='"${{secrets.MAIL_SERVER_ATMOSPHERE}}"' mail_from_name='"${{secrets.MAIL_FROM_NAME_ATMOSPHERE}}"' docker-compose up -d'
